- hosts: servers
  vars:
    nginx_port: 8080
    src_dir: ../files/step_6
    root_dir: /usr/share/nginx/html
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: latest
      become: yes

    - name: Copy index page
      copy:
        src: "{{ src_dir }}/index.html"
        dest: "{{ root_dir }}/index.html"

    - name: Update Nginx config
      template:
        src: "{{ src_dir }}/nginx.conf.j2"
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes
