---
- name: Play for step 8
  hosts: servers
  gather_facts: false
  tasks:
    - name: Install Git
      ansible.builtin.dnf:
        name: git
        state: present
        update_cache: true
      become: true
