---
- name: Play for step 4
  hosts: servers
  vars:
    users_to_add:
      - username: arya
        groups: [stark]
        state: present
        shell: /bin/bash
        create_home: true
        append: true
      - username: sansa
        groups: [stark, lannister]
        state: present
        shell: /bin/bash
        create_home: true
        append: true
      - username: tyrion
        groups: [lannister]
        state: present
        shell: /bin/bash
        create_home: true
        append: true

    groups_to_add:
      - name: stark
      - name: lannister

  tasks:
    - name: Update dnf cache
      ansible.builtin.dnf:
        state: present
        update_cache: true
      tags: package

    - name: Install pkg
      ansible.builtin.dnf:
        name: [git, make, nodejs]
        state: present
      tags: package

    - name: Add starks groups
      ansible.builtin.group:
        name: stark
        state: present
      tags: [user, group]

    - name: Add lannisters group
      ansible.builtin.group:
        name: lannister
        state: present
      tags: [user, group]

    - name: Add user
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: "{{ item.groups | join(', ') }}"
        state: "{{ item.state }}"
        append: "{{ item.append | default(false) }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        create_home: "{{ item.create_home | default('no') }}"
      loop: "{{ users_to_add }}"
      tags: [user, group]
