---
- name: Play for step 5
  hosts: servers
  vars:
    src_path: ../files/step_5
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
      become: true

    - name: Copy index page
      ansible.builtin.copy:
        src: "{{ src_path }}/index.html"
        dest: /usr/share/nginx/html/index.html
        mode: preserve
      become: true

    - name: Update Nginx config
      ansible.builtin.copy:
        src: "{{ src_path }}/nginx.conf"
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify:
        - Restart nginx
      become: true

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
