- hosts: servers
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: latest
      become: yes

    - name: Copy index page
      copy:
        src: ../files/step_5/index.html
        dest: /usr/share/nginx/html/index.html

    - name: Update Nginx config
      copy:
        src: ../files/step_5/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
      become: yes
