- hosts: servers

  vars:
    users_to_add:
      - username: arya
        groups: [stark]
        state: present
        shell: /bin/bash
        create_home: yes
        append: true
      - username: sansa
        groups: [stark, lannister]
        state: present
        shell: /bin/bash
        create_home: yes
        append: true
      - username: tyrion
        groups: [lannister]
        state: present
        shell: /bin/bash
        create_home: yes
        append: true

    groups_to_add:
      - name: stark
      - name: lannister

  tasks:
    - name: update dnf cache
      dnf:
        state: latest
        update_cache: yes
      tags: package

    - name: install pkg
      dnf:
        name: [git, make, nodejs]
        state: present
      tags: package

    - name: add starks groups
      group:
        name: stark
        state: present
      tags: [user, group]

    - name: add lannisters group
      group:
        name: lannister
        state: present
      tags: [user, group]

    - name: add user
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groups | join(', ') }}"
        state: "{{ item.state }}"
        append: "{{ item.append | default(false) }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        create_home: "{{ item.create_home | default('no') }}"
      loop: "{{ users_to_add }}"
      tags: [user, group]
